wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.1
    cli_version: 0.16.0b1
    framework: huggingface
    huggingface_version: 4.34.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698069785.074884
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 100
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 100
      3:
      - 19
      - 23
      4: 3.11.1
      5: 0.16.0b1
      6: 4.34.1
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
TRAIN_BATCH_SIZE:
  desc: null
  value: 2
VALID_BATCH_SIZE:
  desc: null
  value: 2
TRAIN_EPOCHS:
  desc: null
  value: 2
LEARNING_RATE:
  desc: null
  value: 0.0001
SEED:
  desc: null
  value: 42
MAX_LEN:
  desc: null
  value: 512
SUMMARY_LEN:
  desc: null
  value: 150
